- name: Copy hosts file from template
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: Copy hosts file from template
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: check if host already registered
  command: yum repoinfo centos-release-openshift-origin39
  register: subs_result
  failed_when: false
  changed_when: "'This system is not yet registered' in subs_result.stderr"

- name: Install Origin3.9 repo
  command: yum -y install centos-release-openshift-origin39
  retries: 5
  delay: 5
  when: subs_result.changed

- name: Ensure that required packages are present on target hosts
  yum:
    name: "{{item}}"
    state: latest
  retries: 5
  delay: 5
  with_items: "{{packages}}"

- name: Install Required Packages
  yum:
    name: "{{item}}"
    state: installed
  with_items: "{{packages}}"
